### ISSUE TITLE
GroupBy a List

### ISSUE THREAD

**Issue by tony123S** [dart-lang/collection#113]
I use below code to print List

` print(snapshot.data.toList().toString());`
and here the output `[ABC(oid: 343, id: 138), ABC(oid: 344, id: 139),ABC(oid:345,id:138)]`

I trying to group the list based on the id using package collection:

```
  var _reading = snapshot.data[index];
  var newMap = groupBy(snapshot.data.toList(),
                          (obj) => obj[_reading.id]);

```
**Error**

> Class 'ABC' has no instance method '[]'. Receiver: Instance of 'ABC' Tried calling:

**Comment by natebosch** [comment]
It looks like you probably want something more like

```dart
var newMap = groupBay(snapshot.data.toList(), (obj) => obj.id);
```

Though it's hard to say without knowing what `ABC` looks like. Double check the signatures of the functions, the `obj` in this case will have the type of the list, so if it's a `List<ABC>` then `obj` is an `ABC` and will have only those methods and fields.
