### ISSUE TITLE
CombinedMapView not working as expected in Flutter

### ISSUE THREAD

**Issue by Z6P0** [dart-lang/collection#118]
If I run this code

`print(CombinedMapView([{'a': 1}, {'a': 2}]));`

in Dart it prints as expected

`{a: 1}`

but in Flutter it prints

`{a: 1, a: 1}`

Is there a bug or did I miss something?

**Comment by natebosch** [comment]
What version of this package are you using in each case?

This looks like https://github.com/dart-lang/collection/issues/109 - make sure you have at least 1.14.12

I'm going to close this with the assumption that you are on an old version. If you still see this after upgrading to `1.14.12` we can reopen.
