### ISSUE TITLE
Add some extension methods

### ISSUE THREAD

**Issue by natebosch** [dart-lang/collection#121]
This is _technically_ breaking since it introduced the possibility for name conflicts, so we may as well consider them when we'll have a major version bump.

Some methods to consider (edit this comment to add more, we don't need to add them all):

- `Iterable.firstWhereOrNull` since it is no longer feasible to use `Iterable.firstWhere(predicate, orElse: () => null);`
- `List.sortRange`, `List.shuffleRange` - https://github.com/dart-lang/sdk/issues/40841
- `Iterable.enumerate` - https://github.com/dart-lang/sdk/issues/32467
- `Iterable<T?>.whereNotNull()` returns `Iterable<T>`.

All existing top level methods should probably be moved to be extensions.

**Comment by lrhn** [comment]
I would really prefer to introduce a `sublist` functionality where you get a new fixed-length list backed by a slice of another list, then `sortRange(range)` and `shuffleRange(range)` would just be `sublist(range).sort()` and `sublist(range).shuffle()`.
It's annoying to require every operation on lists to have `to`/`from` parameters.
(Ditto for strings, I'd love a lazy substring).

The rest are perfectly reasonable extension method suggestions.

**Comment by natebosch** [comment]
We can't use the name `sublist`, but we could use `slice` or `range`. I do like that idea over `sortRange` and `shuffleRange`.

**Comment by lrhn** [comment]
Extensions have landed
