### ISSUE TITLE
.min/max extension not working on List<int>

### ISSUE THREAD

**Issue by xvrh** [dart-lang/collection#189]
It's surprising that `.min` and `.max` extensions work on a static type `List<num>` but not with `List<int/double>`

```dart
import 'package:collection/collection.dart';

void main() {
  print(<num>[1, 2].min); // OK
  print([1, 2].min); // Static error
  print(<double>[1.0, 2.0].min); // Static error
}
```

**Comment by lrhn** [comment]
It is surprising, but sadly unavoidable. The pattern `<T extends Comparable<T>>` does not match `int` because `int` implements `Comparable<num>`, not `Comparable<int>`.

The same issue applies to Dart generics everywhere, not just extension methods.
