### ISSUE TITLE
wrapper_test has analyzer warnings

### ISSUE THREAD

**Issue by srawlins** [dart-lang/collection#21]
in `wrapper_test.dart`, I see the following with the analyzer:

```
177: [INFO] The getter 'equals' is not defined for the class 'String' [UNDEFINED_GETTER]
263: [INFO] The getter 'equals' is not defined for the class 'String' [UNDEFINED_GETTER]
```

These are because `Expector` is overriding `Object`'s `toString()` with a method that doesn't return a String. Should we change `Expector`'s method to `asString()` or something similar?

**Comment by nex3** [comment]
Ideally, I'd like to rewrite the test to use a more standard style. In the meantime, renaming the parameter is a fine fix if you care about analyzer-cleanliness.
