### ISSUE TITLE
Group By null safe

### ISSUE THREAD

**Issue by realArafatBen** [dart-lang/collection#231]
After switching to null safe, am getting this error when i try grouping 
**_the method '[]' can't be unconditionally invoked because the receiver can be null_** 
my code  
`Map<int, dynamic> newMap = groupBy(data, (obj) => obj['league_id']);` 
did the needful, but still getting this error

**Comment by albertms10** [comment]
You may explicitly specify generic types as [`groupBy<S, T>`](https://api.flutter.dev/flutter/package-collection_collection/groupBy.html):

```dart
final list = ['1', '2', '3'];
Map<int, List<String>> newMap = groupBy<String, int>(list, int.parse);
// {1: [1], 2: [2], 3: [3]}
```

**Comment by realArafatBen** [comment]
ok
