### ISSUE TITLE
Add support for the non linear data structures

### ISSUE THREAD

**Issue by elbeicktalat** [dart-lang/collection#243]
### Proposal
It would be nice if we support the non linear data structures like: trees and graphs.

### Problem
I have been searching for the binary tree, but unfortunately it's not available. So I decided to make my own, but then I realised that would be better if I can contribute to this package instead of making another collection package.

Thanks and I'm sorry for the short description.

**Comment by natebosch** [comment]
We do not currently have plans to publish a core package with representations for trees or graphs.

There is a package under our "tools" publisher which you can use for some graph crawling algorithms. It uses APIs that are independent of the data structure representation you are using. https://pub.dev/packages/graphs
