### ISSUE TITLE
linter: depend_on_referenced_packages

### ISSUE THREAD

**Issue by otopba** [dart-lang/collection#245]
Hi!
Then I use library and import like this:
```dart
import 'package:collection/collection.dart';
```
I see a warning from linter:

https://dart-lang.github.io/linter/lints/depend_on_referenced_packages.html

If I try to use only one extension like this:
```dart
import 'package:collection/src/iterable_extensions.dart';
```

I see a warning from linter:
https://dart-lang.github.io/linter/lints/depend_on_referenced_packages.html

What is the correct way to use a dependency?

**Comment by lrhn** [comment]
You should add a dependency to the package to your `pubspec.yaml` file:

```yaml
dependencies:
  collection: "^2.18.0"
```
should do it.
