### ISSUE TITLE
Feature - Dig a Map to get the latest son with key if it is able to 

### ISSUE THREAD

**Issue by danielgomezrico** [dart-lang/collection#247]
The idea is to have this operator like ruby https://apidock.com/ruby/Hash/dig

# Current
Using `map["first"]["second"]["third"]`  is not null safe, if the `second` does not exist it explodes 

# Expected
The idea is that you can get a value using a nested key easily and without nullability issues:

Something like: `map.dig(["first", "second", "third"])` to fetch 

```dart
group('.dig', () {
    group('with a list of keys', () {
      test('returns the last indented son value one', () {
        final map = {
          "first": {
            "second": {
              "third": "the value",
            }
          }
        };

        final result = map.dig(["first", "second", "third"]);

        expect(result, "the value");
      });
    });
```

# Proposals
1. Using an array:
```dart
map.dig(["first", "second", "third"])
```

1. Using dots ([Like ruby/hash/dig](https://apidock.com/ruby/Hash/dig)):
```dart 
map.dig("first.second.third")
```

**Comment by danielgomezrico** [comment]
I can try with a PR but I would love some guidance, are there any extensions on map yet on this project?

**Comment by lrhn** [comment]
I'd just use `map["first"]?["second"]?["third"]`, then check if the result is `null`.

This preserves the typing of the original nested maps (if they are types, say as `Map<String, Map<String, Map<String, String>>>`. There is no way the `dig` method can preserve that type, which makes it a sub-optimal choice for a generally typed language. I guess it's still useful for untyped JSON-like structures, but I recommend converting those to something better before desturcturing.

Alternatively, wait for patterns and do:

```dart
  if (map case {"first": {"second": {"third": var result, ...}, ...} ,...}) {
     expect(result, "the value");
  }
```

I'd prefer not to add something like `dig` to the current and future Dart language. It's just not well-typed enough.

**Comment by danielgomezrico** [comment]
@Irhn I dont understand the consequence of `if (map case {"fir` whats the purpose of that case inside the if?

**Comment by lrhn** [comment]
The `if`-`case` syntax is one of the currently proposed ways to do [pattern matching](https://github.com/dart-lang/language/issues?q=is%3Aissue+sort%3Aupdated-desc+label%3Apatterns). 

An `if (map case {...}) ...` is practically equivalent to a `switch (map) { case {...}: ...}` pattern match.

The `{"first": {"second": {"third": var result, ...}, ...}, ...}` pattern will match a map with an entry `"first"` and value which is a map with an entry `"second"` and a value which is a map with an entry `"third"` and a value, which is then bound to the new variable `result`.
    
Using pattern matching will allow you to do a deep structural match on the map in one go. When we get it.
