### ISSUE TITLE
[proposal] add Json typedef

### ISSUE THREAD

**Issue by iapicca** [dart-lang/collection#254]
it would be nice if we could  stop using `Map<String,dynamic>` for json
and have something like
```dart
typedef Json = Map<String,Object?>;
```

if find this would 
- reduce bolilerplate
- be more accurate
- be more readable

**Comment by eernstg** [comment]
I'm afraid this approach would not have the required expressive power. You'd probably need something more like this:

```dart
typedef Json = Map<String, Json> | List<Json> | int | double | String | bool;
```

This is _not_ supported by Dart today, nor by any proposal to introduce new features, but this fact serves to illustrate that a reasonably precise model of JSON values (with an arbitrary schema that we're not modeling) requires more expressive power in the typing domain than we can easily express in Dart.

First, the typedef above is recursive, but Dart typedefs do not support recursion. Next, a recursive type like this inherently needs a notion of union types (`|`), such that the recursion can have some atomic cases. Finally, I'd be surprised if you can model JSON using a type that doesn't allow for a simple (primitive) value, like an `int` or a `String`.

So we are pretty far away from being able to model a JSON value in a way that is useful.

One possible approach to this dilemma could be (1) use `typedef Json = dynamic;`, which would allow your JSON values to have all the forms that JSON includes, and then (2) write a JSON verifier function that traverses the entire structure and verifies that each object is one of those cases in the recursive typedef above, replacing `Json` by `dynamic`.

So you'd be able to see that `<String, dynamic>{ 'field': 2 }` is correct JSON, but `<Object, Object>{ 'field': DateTime(...), true: false }` is not.
