### ISSUE TITLE
rewrite whereNotNull without sync*

### ISSUE THREAD

**Issue by mraleph** [dart-lang/collection#273]
Current implementation of `sync*` is suboptimal and we might not get to fixing its performance in Dart 3.0 so we should probably avoid using `sync*` for now.

See also https://github.com/dart-lang/sdk/issues/51806

**Comment by oprypin** [comment]
FWIW a rewrite is already present in the SDK :)

https://github.com/dart-lang/sdk/commit/511bf8a80f71f635b03849ba7f563a70b92833b0#diff-0a7e9eff9502b01ee867e199d3ad5ab32870afcf39b5065970e3504e7834128a
https://github.com/dart-lang/sdk/commit/511bf8a80f71f635b03849ba7f563a70b92833b0#diff-5114558fe685f8eec034675a485cfeee6ff245010ea2b0c8f3f24afa1db9e4d2

**Comment by lrhn** [comment]
We should deprecate the version here, and make it forward to the SDK version.

**Comment by mraleph** [comment]
Should I just abandon the PR or should I make it simply redirect to the SDK implemention (probably requires pubspec.yaml SDK constraint bump).

**Comment by lrhn** [comment]
Whatever we do it should be on the 3.0 branch (which we should land RSN).
