### ISSUE TITLE
New `replaceWhere` method on `List`

### ISSUE THREAD

**Issue by FMorschel** [dart-lang/collection#275]
I would like to propose a new method for `List` called `replaceWhere` or a similar name.

I have some use cases where I have a full list of objects from a class. But something else in my program updates and I would need to (as of right now) save the list, iterate through it and replace it where it matches a test function, for a new value of that same type.

It could probably be something like this:

```dart
Iterable<T> replaceWhere(bool Function(T) test, T Function(T) replace) sync* {
  for (final item in this) {
    if (test(item)) {
      yield replace(item);
    } else {
      yield item;
    }
  }
}

Iterable<T> replaceWhereNot(bool Function(T) test, T Function(T) replace) sync* {
  for (final item in this) {
    if (test(item)) {
      yield item;
    } else {
      yield replace(item);
    }
  }
}
```

**Comment by lrhn** [comment]
This feels like something you can just do with map:
```dart
source.map((e) => test(e) ? replace(e) : e)
```

Which means a declaration of
```dart
extension IterableReplaceWhere<E> on Iterable<E> {
  Iterable<E> replaceWhere(bool Function(E) test, E Function(E) replace) => 
      map((e) => test(e) ? replace(e) : e);
  Iterable<E> replaceWhereNot(bool Function(E) test, E Function(E) replace) => 
      map((e) => test(e) ? e : replace(e));
}
```
would do it.

I don't think it's distinctive enough to warrant its own function, it's just a `map` which happens to have the same type again, and retain some of the values.

I wouldn't  want 
```dart
    Iterable<R> mapWhere<R>(bool Function(E) test, R Function(E) whenMatch, R Function(E) whenNotMatch)) => 
       map((e) => test(e) ? whenMatch(e) : whenNotMatch(e));
```
either. Again it's just too close to `map` with a particular argument, and too specialized, so I'm not convinced it carries its own weight. 

You could also get a lot of the effect by having a helper method:
```dart
  E Function(E) convertIf<E>(bool Function(E) test, E Function(E) convert) => (E e) => test(e) ? convert(e) : e;
```
and doing `iterable.map(convertIf(test, convert))`

We don't want to have a function for every combination of `map` and `where`, things won't get easier to read.
(No matter how often I wish I had a `map + where` or `where + map` combination that only takes one function.)
