### ISSUE TITLE
feature: Please add add a "Pair" class

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/collection#29]
I know it's simple but it's quite often useful:

Something like this:

``` dart
class Pair<T1,T2> {
    final T1 first;
    final T2 second;
    Pair(this.first, this.second);

    bool operator==(final Pair other) {
        return first == other.first && second == other.second;
    }
    int get hashCode => hash2(first.hashCode,second.hashCode);
}
```

**Comment by matanlurey** [comment]
How is this meaningfully different than `package:tuple`?

**Comment by nex3** [comment]
I agree with @matanlurey; the `tuple` package already handles this case well.

**Comment by Soundbytes** [comment]
One of the main usages of a Pair would be to reference a Map entry. 
In that case you don't need tuple. Use MapEntry instead.

(I know this issue was closed long ago. Still I am adding this comment because only recently the answer here did put me on a wrong track.)

**Comment by ride4sun** [comment]
Also adding a package which a simple construct like that sounds just plain wrong - it should be part of dart

**Comment by vanyasem** [comment]
_From tuple.dart's [README](https://github.com/google/tuple.dart/blob/master/README.md):_

With Dart 3.0, users now have
the ability to use [Records](https://dart.dev/language/records):

> Records are an anonymous, immutable, aggregate type. Like other collection
  types, they let you bundle multiple objects into a single object. 

```dart
  var record = (123, true);
  print('${record.$1}: ${record.$2}');
```
