### ISSUE TITLE
Strong mode complains about Equality default constructor params.

### ISSUE THREAD

**Issue by har79** [dart-lang/collection#30]
E.g., "const ListEquality<String>()" causes the following warnings:

[INFO] The object type 'DefaultEquality<E>' cannot be assigned to the field '_elementEquality', which has type 'Equality<String>' [CONST_CONSTRUCTOR_FIELD_TYPE_MISMATCH]
[INFO] The object type 'DefaultEquality<E>' cannot be assigned to a parameter of type 'Equality<String>' [CONST_CONSTRUCTOR_PARAM_TYPE_MISMATCH]

This is because of the type mismatch in ListEquality's default constructor parameters:
final Equality<E> _elementEquality;
const ListEquality([Equality<E> elementEquality = const DefaultEquality()])
    : _elementEquality = elementEquality;

and can be fixed by adding the generic type. I'll send a pull request for this and similar classes.

**Comment by har79** [comment]
Looks like this isn't actually possible in Dart right now due to https://github.com/dart-lang/sdk/issues/22329.

**Comment by nex3** [comment]
What version of collection are you using? I don't see any strong-mode errors with the most recent version.

**Comment by har79** [comment]
1.6.0

**Comment by har79** [comment]
The full line of code that produced the warnings was:
static const _titleEquality = const ListEquality<String>();

I was able to remove the warnings by changing it to:
static const _titleEquality = const ListEquality<String>(const DefaultEquality<String>());

**Comment by nex3** [comment]
What version of Dart are you using? I don't see any strong-mode messages when running the 1.16 analyzer on collection 1.6.0.

**Comment by har79** [comment]
It's v1_17_0_dev_2_0; I can ping you a test link if that helps.

**Comment by nex3** [comment]
I can't reproduce this at all.

```
$ git co 1.6.0
Note: checking out '1.6.0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at e3a6fca... Add GroupSet and SetGroup classes.
$ dartanalyzer-1.17.0-dev.2.0 --version
dartanalyzer version 1.17.0-dev.2.0
$ dartanalyzer-1.17.0-dev.2.0 lib/collection.dart 
Analyzing [lib/collection.dart]...
No issues found
```

I can only guess that you're somehow using a different version of `collection` or of `dartanalyzer` than you think you are.

**Comment by nex3** [comment]
I understand what's happening now; this was hidden when analyzing the libraries themselves due to dart-lang/sdk#26141. It's actually a duplicate of #27.
