### ISSUE TITLE
Index

### ISSUE THREAD

**Issue by tatumizer** [dart-lang/collection#33]
This is the issue for discussion (I don't have a detailed proposal yet).
Index is similar to MapValueSet, it wants to address a couple of extra problems:

1. MapValueSet stores the keys as independent objects. However, the key (by its definition from MapValueSet) can always be reconstructed from the record. Keys pollute memory and increase load on allocator and GC.

2. By construction, MapValueSet assumes the Key to be a public type. Not sure this is necessary. It's hard even to find a good name for the Key class (e.g., XAndY key type for point?)

3. In reality, it all leads to a lot of boilerplate; it would be desirable to have more user-friendly apparatus..

One obvious approach would be:

1. Introduce Index class that accepts Equality as parameter. Due to equality, you can always compare 2 records directly, without creating Key object. Index constructor looks as new Index\<T>(Equality\<T>) 

2. Since there are no "physical" keys, they are not stored anywhere. 

3. To top it off, user is not supposed to write anything manually, b/c we can always define generator like in @davidmorgan's example:

```
part 'point.g.dart';
class Point {
  @Index(#x)
  static final Equality<Point> byX = _$byX;
  @Index(#x, #y)
  static final Equality<Point> byXandY = _$byXandY;

  int x;
  int y;
  // other stuff
}
```

Everything looks good, except that I can't figure out the syntax for search. There should be a method index.find(something).
But how to write this "something", if we, say, want to find a point (2, 2)?

There are several ways. 

- We can create "partial point" (template) containing only fields that constitute the key: points.findByTemplate(new Point(2,2)).

- We can pass tuple: points.find([2, 2])

- We can include createKey() into Equality interface, and call index.find(myEquality.createKey(2,2)). In this case, we don't have to make type K public. And in fact, it might return "template" without defining special type for Key, even private one.

- As a variant, we can call it createTemplate instead of createKey, then it will return record type T.

Do you think the problem is worth solving? I had a couple of situations where it was critical. E.g. there are 3 tables, cross-referenced by composite "relations", - say, several million records each
Suppose you need to run complex (reporting) algo that with many joins (and self-joins) - over entire set. Database operation takes forever. In memory, everything is fast, but indexes (implemented as maps) are eating all memory. 
I had to write something like Index in java, and it was not very easy.

Added later: if we have Index, we need also MultiIndex or something - for one-to-many relation

**Comment by tatumizer** [comment]
BTW, I find the name MapValueSet a bit confusing. It could as well be ValueMapSet or SetMapValue etc. These 3 words don't form a meaningful combination, whatever order you try,  Index is at least a known concept, it's just not quite clear how to formalize it in dart.

**Comment by tatumizer** [comment]
One baby-step towards the Truth: Equality has method isValidKey(Object o). I think it would be logical for it to support also method 

Object createKey(Object keyComponent1, Object keyComponent2, ...).

What do you think?

**Comment by tatumizer** [comment]
Eureka! I figured out what was wrong. I misunderstood your MapValueSet. It has nothing to do with the idea of Index. "Equality" has nothing to do with Index either. I deleted a couple of my earlier comments (it was complete nonsense). 

I will create a new issue for Index (I'm in the process of figuring it out), and then delete this one.  Stay tuned.

**Comment by tatumizer** [comment]
Please close/remove this issue, it's superseded by "Index, take 2"

**Comment by zoechi** [comment]
@tatumizer you should be able to close your own issues.
