### ISSUE TITLE
Index, take 2

### ISSUE THREAD

**Issue by tatumizer** [dart-lang/collection#34]
Index is a familiar concept, would be interesting to see how it fits into dart.

the idea is to write

```
@Indexable(#firstName,#lastName")
class Person {
   final String firstName;
   final String lastName;
   // other stuff
}
```
and run source_gen generator, so we could write

```
var index = new PersonIndex$firstName$lastName();
index.addAll(persons); // some collection of persons
var johnDoe = index.find("John", "Doe");
```

Index is not supposed to create or store keys in the course of normal operation (unless user explicitly wants to get a key).

Generated code contains class  PersonIndex$firstName$lastName extends Index\<Person>
with methods

```
int getHashCode(Person p);
bool haveEqualKeys(Person p1, Person p2);
bool hasKey(Person p1, Object key)
bool isValidKey(Object key)
Person find(String firstName, String lastName);
Object extractKey(Person p); // rarely needed
// other blows and whistles
```

For key extraction, generator generates also PersonKey$firstName$lastName

The whole idea is to make it more convenient and save memory on keys. Generated classes will have quite a bit of redundancy. Writing it manually is not worth it.

**Comment by tatumizer** [comment]
For curiosity, tested quick-and-dirty implementation of Index - there's 15-20% gain in performance (on top of obvious memory gains).

**Comment by nex3** [comment]
This sounds like a great opportunity for its own package, but I don't think it belongs in `collection`.
