### ISSUE TITLE
Proposal: Equality<E>.from(<closure>)

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/collection#38]
There should be a less verbose way to create an `Equality` implementation for:

```dart
abstract class Employee {
  int get idNumber;
  String get name;
}

void main() {
  final equality = new Equality<Employee>.from((e) => e.idNumber);
  assert(
    equality.equals(new Employee(idNumber: 5), new Employee(idNumber: 5)),
  );
}
```

An implementation example:

```dart
typedef Object _GetKey<E>(E object);

class _ClosureEquality<E> implements Equality<E> {
  final _GetKey<E> _getKey;

  _ClosureEquality(Object getKey(E object)) : this._getKey = getKey;

  @override
  bool isValidKey(Object o) => o is E;

  @override
  int hash(E e) => _getKey(e).hashCode;

  @override
  bool equals(E e1, E e2) => _getKey(e1) == _getKey(e2);
}
```

**Comment by nex3** [comment]
I like the idea, but I'm not sure I like the name. Without further context, I'd expect `Equality.from()` to take closures for `equals()` and `hash()`. What about `Equality.by()`, like you might say "the employees are equal by ID?"

It would also be good to include an optional parameter to define how the closure results are compared. Unfortunately factory constructors can't have method-level generics, so you'd have to define a new class to type this properly:

```dart
class EqualityBy<E, F> implements Equality<E> {
  EqualityBy(F getKey(E object), [Equality<F> inner]);
}
```

**Comment by matanlurey** [comment]
I admit I am the _worst_ at naming. I like `Equality.by()` 👍 

If you're OK with the API / changes, I'll start on a PR.

**Comment by nex3** [comment]
Go for it.
