### ISSUE TITLE
Documentation link is broken at https://pub.dartlang.org/packages/collection

### ISSUE THREAD

**Issue by leiboldm** [dart-lang/collection#42]
It currently links to https://www.dartdocs.org/documentation/collection/1.12.0/ which returns a 404 error.

**Comment by nex3** [comment]
It looks like [the build is failing](https://www.dartdocs.org/documentation/collection/1.12.0/log.txt) due to the current SDK constraint, but that seems to violate semver. I'll investigate this from the pub side.

**Comment by nex3** [comment]
As far as I know, dartdocs.org is currently unable to generate documentation for packages that are incompatible with the latest stable SDK version, which collection currently is. I don't think there's much we can do about this right now.

**Comment by franklinyu** [comment]
`collection` is incompatible with the latest stable SDK version? Why is that the case? The `pubspec.yaml` specifies `>=1.21.0-dev.1.0 <2.0.0` which should be compatible with `1.21.0`, is it?

**Comment by nex3** [comment]
@franklinyu The documentation was generated, and that comment was written, before 1.21.0 stable had been released.

**Comment by franklinyu** [comment]
@nex3 Which means that documentation for the next release will probably be good, right? Since I managed to compile it locally.

**Comment by nex3** [comment]
Hopefully!

**Comment by franklinyu** [comment]
I made a temporary alternative before the official documentation get updated: <https://dart-collection-doc.firebaseapp.com>. It's free (since there is no database)! Just in case somebody wants it now.

If only dart Pub has a "force rebuild" button...

**Comment by nex3** [comment]
> If only dart Pub has a "force rebuild" button...

Feel free to file an issue on [the dartdocs.org repo](https://github.com/astashov/dartdocs.org/issues).

**Comment by franklinyu** [comment]
It's there! 🎉
