### ISSUE TITLE
PriorityQueue and comparison function inconsistent

### ISSUE THREAD

**Issue by floitschG** [dart-lang/collection#45]
The documentat of `PriorityQueue` states:
```
  /// The [comparison] is a [Comparator] used to compare the priority of
  /// elements. An element that compares as less than another element has
  /// a higher priority.
```

(btw: the documentation doesn't state what the function should return).

However, the comparison function is also used as equality function.
For example, `PriorityQueue.contains`, or `PriorityQueue.remove` both use this function to determine equality. In some cases that works, but a common use case is to extract a priority field from one of many fields.

Example:
``` dart
class PriorityPoint {
  int x, y, priority;
  PriorityPoint(this.x, this.y, this.priority);
}

var queue = new PriorityQueue(comparison: (p1, p2) => p2.priority - p1.priority);
queue.add(new PriorityPoint(0, 1, 5));
queue.contains(new PriorityPoint(-1, -3, 5));  // Should probably return false.
```

I'm not sure what the best solution is, but the current behavior and documentation are not consistent.
Furthermore, the current behavior makes it hard to implement the provided use case.

**Comment by nex3** [comment]
I think we can probably just switch to a normal equality comparison here. I only see a couple uses within Google, and they don't seem to rely on the busted equality behavior. I doubt there are any that do externally, and semantically this could definitely be considered a bug.

**Comment by floitschG** [comment]
It might be hard to be as efficient, though.
For example, if all items have the same priority, then `contains` suddenly becomes an O(n) operation.
In theory we should then use the hashcodes (or something similar) to make the lookups faster.

**Comment by nex3** [comment]
> It might be hard to be as efficient, though.
> For example, if all items have the same priority, then `contains` suddenly becomes an O(n) operation.
> In theory we should then use the hashcodes (or something similar) to make the lookups faster.

I don't think this is necessarily that big of a deal. I think users would reasonably expect something with "Queue" in its name to have O(n) contains.

**Comment by matanlurey** [comment]
This has been open since 2016 without action so I am closing as stale.

**Comment by nex3** [comment]
Re-opening as per https://github.com/dart-lang/collection/issues/6#issuecomment-372500079.Re-opening as per https://github.com/dart-lang/collection/issues/6#issuecomment-372500079.

**Comment by lrhn** [comment]
We should fix this. A queue can contain the same element more than once, so it should not be an issue to contain different elements with the same priority either. The `remove` should be equality based, but I think it's safe to require that equal objects have equal priorities, so we can still use the comparator to find potential candidiates for `==`-checks.
