### ISSUE TITLE
Consider `Map<V, K> flipMap<K, V>(Map<K, V> map)`

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/collection#56]
As a short-hand (and even potentially implemented with) for:

```dart
mapMap(map, key: (k, v) => v, value: (k, v) => k)
```

This is much cheaper than a full `BiMap` implementation when you just need it flipped once.

Thoughts?

**Comment by nex3** [comment]
That `mapMap()` call is pretty short... does it really need a shorthand?
