### ISSUE TITLE
Fails compilation with dartdevc

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/collection#60]
```
[error] Missing field type for 'key'. (package:collection/src/equality.dart, line 268, col 9)
[error] Missing field type for 'value'. (package:collection/src/equality.dart, line 269, col 9)
[error] A value of type 'Object' can't be assigned to a variable of type '_MapEntry'. (package:collection/src/equality.dart, line 279, col 28)
[error] Missing type arguments for generic type 'Equality<dynamic>'. (package:collection/src/equality.dart, line 397, col 41)
[error] Missing type arguments for generic type 'DefaultEquality<dynamic>'. (package:collection/src/equality.dart, line 400, col 55)
[error] Missing type arguments for generic type 'DefaultEquality<dynamic>'. (package:collection/src/equality.dart, line 408, col 30)
[error] Missing parameter type for 'e1'. (package:collection/src/equality.dart, line 412, col 15)
[error] Missing parameter type for 'e2'. (package:collection/src/equality.dart, line 412, col 19)
[error] Missing type arguments for generic type 'SetEquality<dynamic>'. (package:collection/src/equality.dart, line 415, col 18)
[error] The argument type 'dynamic' can't be assigned to the parameter type 'Set'. (package:collection/src/equality.dart, line 415, col 47)
[error] Missing type arguments for generic type 'MapEquality<dynamic, dynamic>'. (package:collection/src/equality.dart, line 419, col 18)
[error] The argument type 'dynamic' can't be assigned to the parameter type 'Map'. (package:collection/src/equality.dart, line 419, col 67)
[error] Missing type arguments for generic type 'ListEquality<dynamic>'. (package:collection/src/equality.dart, line 424, col 20)
[error] The argument type 'dynamic' can't be assigned to the parameter type 'List'. (package:collection/src/equality.dart, line 424, col 50)
[error] Missing type arguments for generic type 'IterableEquality<dynamic>'. (package:collection/src/equality.dart, line 428, col 20)
[error] The argument type 'dynamic' can't be assigned to the parameter type 'Iterable'. (package:collection/src/equality.dart, line 428, col 54)
[error] Missing type arguments for generic type 'UnorderedIterableEquality<dynamic>'. (package:collection/src/equality.dart, line 433, col 18)
[error] The argument type 'dynamic' can't be assigned to the parameter type 'Iterable'. (package:collection/src/equality.dart, line 433, col 61)
[error] Missing type arguments for generic type 'SetEquality<dynamic>'. (package:collection/src/equality.dart, line 439, col 30)
[error] Missing type arguments for generic type 'MapEquality<dynamic, dynamic>'. (package:collection/src/equality.dart, line 440, col 30)
[error] Missing type arguments for generic type 'ListEquality<dynamic>'. (package:collection/src/equality.dart, line 442, col 33)
[error] Missing type arguments for generic type 'IterableEquality<dynamic>'. (package:collection/src/equality.dart, line 443, col 37)
[error] Missing type arguments for generic type 'UnorderedIterableEquality<dynamic>'. (package:collection/src/equality.dart, line 445, col 18)

Please fix all errors before compiling (warnings are okay).

Error compiling dartdevc module:collection|lib/lib__shared_1.js

[error] Missing variable type for 'tmp1'. (package:collection/src/algorithms.dart, line 74, col 9)
[error] Missing variable type for 'tmp'. (package:collection/src/algorithms.dart, line 89, col 9)
[error] Missing type arguments for generic function '_mergeSort<T>'. (package:collection/src/algorithms.dart, line 228, col 3)

Please fix all errors before compiling (warnings are okay).

Error compiling dartdevc module:collection|lib/lib__shared_2.js

[error] Missing parameter type for 'element'. (package:collection/src/typed_wrappers.dart, line 39, col 27)
[error] Missing parameter type for 'element'. (package:collection/src/typed_wrappers.dart, line 47, col 42)
[error] Missing parameter type for 'value'. (package:collection/src/typed_wrappers.dart, line 61, col 21)
[error] Missing parameter type for 'element'. (package:collection/src/typed_wrappers.dart, line 61, col 28)
[error] Missing parameter type for 'value'. (package:collection/src/typed_wrappers.dart, line 91, col 8)
[error] The return type 'Iterable' isn't a 'List', as defined by the method '_listBase'. (package:collection/src/typed_wrappers.dart, line 111, col 25)
[error] Missing parameter type for 'a'. (package:collection/src/typed_wrappers.dart, line 197, col 23)
[error] Missing parameter type for 'b'. (package:collection/src/typed_wrappers.dart, line 197, col 26)
[error] The return type 'Iterable' isn't a 'Set', as defined by the method '_setBase'. (package:collection/src/typed_wrappers.dart, line 212, col 23)
[error] The return type 'Iterable' isn't a 'Queue', as defined by the method '_baseQueue'. (package:collection/src/typed_wrappers.dart, line 263, col 27)
[error] Missing parameter type for 'key'. (package:collection/src/typed_wrappers.dart, line 328, col 20)
[error] Missing parameter type for 'value'. (package:collection/src/typed_wrappers.dart, line 328, col 25)
[error] The return type 'Iterable<E>' isn't a 'List<E>', as defined by the method '_listBase'. (package:collection/src/wrappers.dart, line 128, col 28)
[error] The return type 'Iterable<E>' isn't a 'Set<E>', as defined by the method '_setBase'. (package:collection/src/wrappers.dart, line 237, col 26)
[error] The return type 'Iterable<E>' isn't a 'Queue<E>', as defined by the method '_baseQueue'. (package:collection/src/wrappers.dart, line 302, col 30)
[error] Missing type argument for list literal. (package:collection/src/wrappers.dart, line 570, col 20)
[error] Missing type argument for list literal. (package:collection/src/wrappers.dart, line 587, col 24)

Please fix all errors before compiling (warnings are okay).
```

**Comment by jmesserly** [comment]
From those error messages, it looks like you compiled with `--no-implicit-casts` and `--no-implicit-dynamic`? Was that intended? I've seen it happen when there's a `.analysis_options` in a parent directory that has those options set.

**Comment by egorov** [comment]
Same error. I've got the fresh copy of official Angular Dart architecture examples repository and I tried to build it. Full log:

	git clone git@github.com:angular-examples/architecture.git
    Клонирование в «architecture»…
	Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.
	Enter passphrase for key '/home/se/.ssh/id_rsa': 
	remote: Counting objects: 5628, done.
	remote: Total 5628 (delta 0), reused 0 (delta 0), pack-reused 5628
	Получение объектов: 100% (5628/5628), 3.84 MiB | 491.00 KiB/s, готово.
	Определение изменений: 100% (5013/5013), готово.

	cd architecture/

	pub get
	Resolving dependencies... (11.7s)
	Overriding the upper bound Dart SDK constraint to <=2.0.0-dev.2.0 for the following packages:
	
	analyzer, angular, angular_compiler, angular_forms, args, async, barback, browser, build, build_barback, charcode, cli_util, code_builder, code_transformers, collection, convert, crypto, csslib, dart_style, dart_to_js_script_rewriter, developer_guide_intro, front_end, func, glob, html, intl, isolate, js, kernel, logging, matcher, meta, package_config, path, pool, quiver, quiver_hashcode, source_gen, source_maps, source_span, stack_trace, string_scanner, tuple, utf, watcher, yaml
	
	To disable this you can set the PUB_ALLOW_PRERELEASE_SDK system environment variable to `false`, or you can silence this message by setting it to `quiet`.
	+ analyzer 0.30.0+4 (0.31.0-alpha.1 available)
	+ angular 4.0.0
	+ angular_compiler 0.3.0
	+ angular_forms 1.0.0
	+ args 1.0.0
	+ async 1.13.3 (2.0.0 available)
	+ barback 0.15.2+12
	+ browser 0.10.0+2
	+ build 0.10.2
	+ build_barback 0.4.0+1
	+ charcode 1.1.1
	+ cli_util 0.1.2+1
	+ code_builder 1.0.4 (2.0.0-alpha+1 available)
	+ code_transformers 0.5.1+3
	+ collection 1.14.3
	+ convert 2.0.1
	+ crypto 2.0.2+1
	+ csslib 0.14.1
	+ dart_style 1.0.8
	+ dart_to_js_script_rewriter 1.0.3
	+ front_end 0.1.0-alpha.4.1 (0.1.0-alpha.6 available)
	+ func 1.0.0
	+ glob 1.1.5
	+ html 0.13.2
	+ intl 0.15.1
	+ isolate 1.1.0
	+ js 0.6.1
	+ kernel 0.3.0-alpha.1.1 (0.3.0-alpha.3 available)
	+ logging 0.11.3+1
	+ matcher 0.12.1+4
	+ meta 1.1.2
	+ package_config 1.0.3
	+ path 1.4.2
	+ plugin 0.2.0+1
	+ pool 1.3.3
	+ quiver 0.25.0
	+ quiver_hashcode 1.0.0
	+ source_gen 0.7.1
	+ source_maps 0.10.4
	+ source_span 1.4.0
	+ stack_trace 1.8.2
	+ string_scanner 1.0.2
	+ tuple 1.0.1
	+ typed_data 1.1.4
	+ utf 0.9.0+3
	+ watcher 0.9.7+4
	+ yaml 2.1.13
	Changed 47 dependencies!
	Precompiling dependencies... 
	Loading source assets... 
	Loading angular and dart_to_js_script_rewriter transformers... (4.2s)
	Precompiled angular, angular_forms, dart_style, dart_to_js_script_rewriter and intl.
    
	pub build --web-compiler=dartdevc
	Loading source assets... 
	Loading angular and dart_to_js_script_rewriter transformers... 
	Building developer_guide_intro... (47.7s)
	Building dartdevc modules... (10.5s)
	Error compiling dartdevc module:angular|lib/lib__shared_2.js
	
	[error] The argument type '(Zone, ZoneDelegate, Zone, () → dynamic) → dynamic' can't be assigned to the parameter type '<R>(Zone, ZoneDelegate, Zone, () → R) → R'. (package:angular/src/core/zone/ng_zone.dart, line 144, col 13)
	[error] The argument type '(Zone, ZoneDelegate, Zone, (dynamic) → dynamic, dynamic) → dynamic' can't be assigned to the parameter type '<R,T>(Zone, ZoneDelegate, Zone, (T) → R, T) → R'. (package:angular/src/core/zone/ng_zone.dart, line 145, col 13)
	[error] The argument type '(Zone, ZoneDelegate, Zone, (dynamic, dynamic) → dynamic, dynamic, dynamic) → dynamic' can't be assigned to the parameter type '<R,T1,T2>(Zone, ZoneDelegate, Zone, (T1, T2) → R, T1, T2) → R'. (package:angular/src/core/zone/ng_zone.dart, line 146, col 13)
	[error] The return type 'void' isn't a 'R', as defined by the method 'runGuarded'. (package:angular/src/core/zone/ng_zone.dart, line 310, col 12)
	
	Please fix all errors before compiling (warnings are okay).
	
	Build failed.
