### ISSUE TITLE
Add SetQueue class

### ISSUE THREAD

**Issue by pschiffmann** [dart-lang/collection#72]
_Copied from [the sdk issue repo](https://github.com/dart-lang/sdk/issues/32386)_

I need a queue that automatically sorts out duplicates. Right now I do:
```dart
final queue = new Set<Something>();
while (queue.isNotEmpty) {
  final something = queue.first;
  queue.remove(something);
  process(something);
}
```

But having a dedicated class for that would be nice. I can try to implement it, but I'll need help when it comes to benchmarking. (compare [sdk/31470](https://github.com/dart-lang/sdk/issues/31470)?)

... if you think this class belongs in this package, of course.

**Comment by nex3** [comment]
Something like this could be nice. We already have [`QueueList`](https://www.dartdocs.org/documentation/collection/latest/collection/QueueList-class.html), so there's prior art for adding queue functionality on top of existing collections.

**Comment by lrhn** [comment]
It should be possible to achieve queue FIFO behavior and deduplication functionality simply by using a `LinkedHashSet` with `add` and `set.remove(set.first)`. 
I don't see a good data structure that would improve over that in performance or usability. I'd probably just add a `removeFirst()` extension method to sets where I needed the behavior.
