### ISSUE TITLE
Remove "prefer_single_quotes"  lint or fix repository

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/collection#75]
It's not fair to introduce _1600_ analysis hints in a repository without either fixing it, having a plan to fix it, etc. This is just noise for the average developer and doesn't help anyone.

<img width="498" alt="screen shot 2018-03-12 at 9 10 53 am" src="https://user-images.githubusercontent.com/168174/37295385-4c4b4ce6-25d5-11e8-9768-61e23fba3878.png">

I'm proposing removing this lint pending some sort of "fix all" from the analyzer.

/cc @kevmoo

**Comment by kevmoo** [comment]
Remove the lint. I'll approve the PR
